name: CloudRun GCP CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install --force
        
    - name: Build
      run: npm run build

    - name: Configure Docker login
      uses: docker/login-action@v1
      with:
        registry: us-east-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Build and push Docker image
      run: |
        docker build -t us-east-docker.pkg.dev/projeto-base/docker-images-repo/api-model .
        docker push us-east-docker.pkg.dev/projeto-base/docker-images-repo/api-model
  CD:
    runs-on: ubuntu-latest
    needs: CI
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: projeto-base
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy api-model \
          --image us-east-docker.pkg.dev/projeto-base/docker-images-repo/api-model \
          --platform managed \
          --region us-east 